/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { KatakanaData } from './types';

export const katakanaList: KatakanaData[] = [
  {
    char: 'ア',
    kanji: '阿',
    part: '「阿」の偏（左側の「阝」）',
    originDetail: '「阿（ア）」という漢字の左側にある「おざと・こざとへん（阝）」が、そのまま取り出されて「ア」になりました。',
    strokeCount: 2,
    romaji: 'a',
    type: 'hen',
    typeName: '偏（ひだり）',
    visualTips: '「阿」の左側「阝」の角を落として滑らかにすると「ア」の形になります。',
    meaning: 'おもねる、大きな丘、川のくま',
    dummyKanji: ['何', '河', '可']
  },
  {
    char: 'イ',
    kanji: '伊',
    part: '「伊」の偏（左側の「亻」）',
    originDetail: '「伊（イ）」という漢字の左側にある「にんべん（亻）」が、そのままカタカナの「イ」になりました。',
    strokeCount: 2,
    romaji: 'i',
    type: 'hen',
    typeName: '偏（ひだり）',
    visualTips: '「にんべん」そのものが「イ」なので、もっとも分かりやすい成り立ちの一つです。',
    meaning: 'これ、かれ、伊豆や伊勢などの地名',
    dummyKanji: ['仲', '任', '位']
  },
  {
    char: 'ウ',
    kanji: '宇',
    part: '「宇」の冠（上側の「宀」）',
    originDetail: '「宇（ウ）」という漢字の上部にある部首「うかんむり（宀）」が、そのまま「ウ」になりました。',
    strokeCount: 3,
    romaji: 'u',
    type: 'kanmuri',
    typeName: '冠（かんむり）',
    visualTips: '「うかんむり（宀）」そのものが「ウ」です。ひらがなの「う」も同じ「宇」全体の草書から作られました。',
    meaning: 'いえ、大空、宇宙、包み込む',
    dummyKanji: ['守', '完', '安']
  },
  {
    char: 'エ',
    kanji: '江',
    part: '「江」の旁（右側の「工」）',
    originDetail: '「江（コウ・エ）」という漢字の右側にある「工（コウ）」の部分が取り出されて「エ」になりました。',
    strokeCount: 3,
    romaji: 'e',
    type: 'tsukuri',
    typeName: '旁（つくり・みぎ）',
    visualTips: '「さんずい（氵）」をなくして、右側の「工」だけを書くとカタカナの「エ」になります。',
    meaning: '大きな川、入り江',
    dummyKanji: ['紅', '工', '功']
  },
  {
    char: 'オ',
    kanji: '於',
    part: '「於」の偏（左側の「方」に似た部分）',
    originDetail: '「於（オ・ヨ）」という漢字の左側の「方」に似た部分が変形して「オ」になりました。',
    strokeCount: 3,
    romaji: 'o',
    type: 'hen',
    typeName: '偏（ひだり）',
    visualTips: '「於」の左側「方」の縦棒と右上の点が交差し、すっきりと整理されて「オ」の形になりました。',
    meaning: '〜において、〜における（場所や時間を表す）',
    dummyKanji: ['放', '旗', '施']
  },
  {
    char: 'カ',
    kanji: '加',
    part: '「加」の偏（左側の「力」）',
    originDetail: '「加（カ）」という漢字の左側にある「力（ちから）」の部分がそのまま「カ」になりました。',
    strokeCount: 2,
    romaji: 'ka',
    type: 'hen',
    typeName: '偏（ひだり）',
    visualTips: '「加」の右側の「口」を取り除き、「力」だけを残して少し角度をつけたのが「カ」です。ひらがなの「か」も同じく「加」が由来です。',
    meaning: '加える、増やす、仲間入りする',
    dummyKanji: ['架', '力', '賀']
  },
  {
    char: 'キ',
    kanji: '幾',
    part: '「幾」の上部の一部',
    originDetail: '「幾（キ）」という漢字の上部にある「幺（よう）」が二つ並んだ部分の草書体から、簡略化されて「キ」になりました。',
    strokeCount: 3,
    romaji: 'ki',
    type: 'part',
    typeName: '一部の省略',
    visualTips: '「幾」の上の部分を崩して書く中で、横棒二本と斜めの一棒が残り、「キ」の形になりました。',
    meaning: 'いくつの、ちかい、兆し、細かい',
    dummyKanji: ['機', '畿', '気']
  },
  {
    char: 'ク',
    kanji: '久',
    part: '「久」の左上部分（最初の二画）',
    originDetail: '「久（キュウ・ク）」という漢字の左上の最初の二画（クに似た部分）が取り出されて「ク」になりました。',
    strokeCount: 2,
    romaji: 'ku',
    type: 'part',
    typeName: '一部の省略',
    visualTips: '「久」の最後の右払いの線（捺）を省略して、左側の部分だけを書くと「ク」になります。',
    meaning: '長い時間が経つ、ひさしい',
    dummyKanji: ['及', '内', '欠']
  },
  {
    char: 'ケ',
    kanji: '介',
    part: '「介」の全体（崩し字・省略）',
    originDetail: '「介（カイ・ケ）」という漢字全体の草書体（くずし字）がさらに省略され、カタカナの「ケ」になりました。',
    strokeCount: 3,
    romaji: 'ke',
    type: 'full',
    typeName: '全体の変形',
    visualTips: '「介」の上部を「ク」のように書き、下部の左払いを省略して縦棒を引くことで「ケ」が生まれました。',
    meaning: '仲介する、あいだに立つ、助ける、身につける',
    dummyKanji: ['分', '公', '合']
  },
  {
    char: 'コ',
    kanji: '己',
    part: '「己」の上部（最初の一・二画）',
    originDetail: '「己（コ・キ）」という漢字の上部の部分（最初の角を曲がる二画）が取り出されて「コ」になりました。',
    strokeCount: 2,
    romaji: 'ko',
    type: 'part',
    typeName: '一部の省略',
    visualTips: '「己」の一番下の底辺の線を書かずに、上のコの字部分だけで止めたのが「コ」です。',
    meaning: 'おのれ、自分、つちのと',
    dummyKanji: ['已', '巳', '弓']
  },
  {
    char: 'サ',
    kanji: '散',
    part: '「散」の左上部分',
    originDetail: '「散（サン・サ）」という漢字の左上部（「サ」の字に似た草冠のような部分）がそのまま「サ」になりました。',
    strokeCount: 3,
    romaji: 'sa',
    type: 'part',
    typeName: '一部の省略',
    visualTips: '「散」の左上の、横棒に縦棒が二本交差する部分をすっきりと取り出したのが「サ」です。',
    meaning: '散る、ばらばらになる、分ける',
    dummyKanji: ['敬', '数', '敷']
  },
  {
    char: 'シ',
    kanji: '之',
    part: '「之」の草書体（全体の崩し）',
    originDetail: '「之（シ）」という漢字の草書体（くずし字）の点と線の位置関係が整理されて、カタカナの「シ」になりました。',
    strokeCount: 3,
    romaji: 'shi',
    type: 'full',
    typeName: '全体の変形',
    visualTips: '「之」を草書で書くと、右上から下へ、そして右へ流れるような筆の動きになり、それが三つの点・線（シ）に整理されました。',
    meaning: '〜の、これ、行く',
    dummyKanji: ['芝', '乏', '志']
  },
  {
    char: 'ス',
    kanji: '須',
    part: '「須」の旁（右側の「頁」の下部）',
    originDetail: '「須（ス）」という漢字の右側にある「頁（おおがい）」の下部の「ハ」に似た部分、または全体の草書から省略されて「ス」になりました。',
    strokeCount: 2,
    romaji: 'su',
    type: 'part',
    typeName: '一部の省略',
    visualTips: '「須」の右側の最後、脚にあたる二画が変化し、交差して「ス」の形になりました。',
    meaning: '用いる、必要とする、しばらく、まつ',
    dummyKanji: ['順', '頭', '頑']
  },
  {
    char: 'セ',
    kanji: '世',
    part: '「世」の全体（省略・変形）',
    originDetail: '「世（セイ・セ）」という漢字の行書・草書体から、いくつかの線を省略して「セ」が作られました。',
    strokeCount: 2,
    romaji: 'se',
    type: 'full',
    typeName: '全体の変形',
    visualTips: '「世」の真ん中の縦棒と右側の縦棒が繋がり、最後の一画が省略されて、すっきりした「セ」になりました。',
    meaning: 'よ、世の中、世代、三十年',
    dummyKanji: ['冊', '廿', '甘']
  },
  {
    char: 'ソ',
    kanji: '曽',
    part: '「曽」の上部（最初の二画「丷」）',
    originDetail: '「曽（ソウ・ソ）」という漢字の最上部にある二本の短い点（「丷」の部分）がそのまま「ソ」になりました。',
    strokeCount: 2,
    romaji: 'so',
    type: 'part',
    typeName: '一部の省略',
    visualTips: '「曽」の頭に乗っている二つの点を少し斜めに大きく書いたものが「ソ」です。',
    meaning: 'かつて、かさねる、ひいおじいさん（曾孫など）',
    dummyKanji: ['普', '尊', '首']
  },
  {
    char: 'タ',
    kanji: '多',
    part: '「多」の上半分（上の「タ」に似た部分）',
    originDetail: '「多（タ）」という漢字は「夕」が二つ重なっていますが、その上側の「夕」の部分が取り出されて「タ」になりました。',
    strokeCount: 3,
    romaji: 'ta',
    type: 'part',
    typeName: '一部の省略',
    visualTips: '「多」の上下重なっているうち、上の「夕」をそのまま抜き出すと「タ」になります。',
    meaning: 'おおい、たくさん、まさる',
    dummyKanji: ['夕', '名', '外']
  },
  {
    char: 'チ',
    kanji: '千',
    part: '「千」の全体（崩し・変形）',
    originDetail: '「千（セン・チ）」という漢字全体の形が、少し斜めに、書きやすく整理されて「チ」になりました。',
    strokeCount: 3,
    romaji: 'chi',
    type: 'full',
    typeName: '全体の変形',
    visualTips: '「千」の一画目の斜め払いを少し長めにし、二画目の横棒と三画目の縦棒をバランスよく配置したのが「チ」です。',
    meaning: 'ち、かずの千、非常に多いこと',
    dummyKanji: ['干', '午', '牛']
  },
  {
    char: 'ツ',
    kanji: '川',
    part: '「川」の草書体（変形）',
    originDetail: '「川（セン・かわ）」という漢字の草書体（くずし字）において、三つの縦線が流れるように点へと変化したものだ「ツ」になりました。',
    strokeCount: 3,
    romaji: 'tsu',
    type: 'full',
    typeName: '全体の変形',
    visualTips: '「川」の縦に長い三本の線が、素早く書くことで「斜めの三つの点」に変化し、現在の「ツ」になりました。',
    meaning: 'かわ、みずの流れ',
    dummyKanji: ['州', '訓', '巡']
  },
  {
    char: 'テ',
    kanji: '天',
    part: '「天」の草書体（省略・変形）',
    originDetail: '「天（テン）」という漢字の草書体の上半分、あるいは全体を素早く書く過程で簡略化されて「テ」になりました。',
    strokeCount: 3,
    romaji: 'te',
    type: 'full',
    typeName: '全体の変形',
    visualTips: '「天」の上の二本の横棒と、左払いの線が繋がり、右払いが消えることで「テ」の形になります。',
    meaning: 'てん、そら、あめ、自然、生まれつき',
    dummyKanji: ['夫', '矢', '失']
  },
  {
    char: 'ト',
    kanji: '止',
    part: '「止」の右上部分（最初の一・二画）',
    originDetail: '「止（シ・とまる）」という漢字の最初の一画（縦棒）と二画（右へ出る横棒）の組み合わせが「ト」になりました。',
    strokeCount: 2,
    romaji: 'to',
    type: 'part',
    typeName: '一部の省略',
    visualTips: '「止」の上の部分（トの形）だけを取り出し、下の土台部分を省略したのが「ト」です。',
    meaning: 'とまる、とどめる、ふるまい',
    dummyKanji: ['上', '正', '歩']
  },
  {
    char: 'ナ',
    kanji: '奈',
    part: '「奈」の左上部分（最初の二画）',
    originDetail: '「奈（ナ）」という漢字の左上にある、横棒と斜め左払いの二画（「ナ」に似た部分）がそのまま取り出されて「ナ」になりました。',
    strokeCount: 2,
    romaji: 'na',
    type: 'part',
    typeName: '一部の省略',
    visualTips: '「奈」の下にある「示」の部分をすべて省略し、上の冠（大）の最初の二画だけを残したのが「ナ」です。ひらがなの「な」も同じく「奈」が由来です。',
    meaning: 'からなし（梨の一種）、いかん（どうして）、奈良などの地名',
    dummyKanji: ['余', '茶', '奈良']
  },
  {
    char: 'ニ',
    kanji: '仁',
    part: '「仁」の旁（右側の「二」）',
    originDetail: '「仁（ジン・ニ）」という漢字の右側（旁＝つくり）にある「二」の部分が、そのまま「ニ」になりました。',
    strokeCount: 2,
    romaji: 'ni',
    type: 'tsukuri',
    typeName: '旁（つくり・みぎ）',
    visualTips: '「にんべん（亻）」を取り除き、右側の「二（ふたつ）」だけを残したのが「ニ」です。数字の二とも同じ形です。',
    meaning: 'おもいやり、いつくしみ、じん、ひと',
    dummyKanji: ['仕', '他', '代']
  },
  {
    char: 'ヌ',
    kanji: '奴',
    part: '「奴」の旁（右側の「又」）',
    originDetail: '「奴（ド・ヌ）」という漢字の右側（旁＝つくり）にある「又（また）」の部分が変化して「ヌ」になりました。',
    strokeCount: 2,
    romaji: 'nu',
    type: 'tsukuri',
    typeName: '旁（つくり・みぎ）',
    visualTips: '「奴」の左側の「女」を省略し、右側の「又」の角を少し丸く省略してつなげて書いたのが「ヌ」です。',
    meaning: 'めした、奴隷、やつ、しもべ',
    dummyKanji: ['好', '怒', '如']
  },
  {
    char: 'ネ',
    kanji: '祢',
    part: '「祢（禰）」の偏（左側の「礻」）',
    originDetail: '「祢（ネ・ね）」という漢字の左側にある部首「しめすへん（礻）」の行書体（ネの形）が、そのまま「ネ」になりました。',
    strokeCount: 4,
    romaji: 'ne',
    type: 'hen',
    typeName: '偏（ひだり）',
    visualTips: '「しめすへん」が楷書で「礻」になり、これをさらに手書きで滑らかにした「ネ」の形そのものです。',
    meaning: 'みたまや、祖先を祀る神殿',
    dummyKanji: ['神', '社', '祖']
  },
  {
    char: 'ノ',
    kanji: '乃',
    part: '「乃」の最初の一画',
    originDetail: '「乃（ナイ・ノ）」という漢字の左側の斜め下にスッと払う一画目が、そのままカタカナの「ノ」になりました。',
    strokeCount: 1,
    romaji: 'no',
    type: 'part',
    typeName: '一部の省略',
    visualTips: '「乃」の二画目の「弓」に似た右側の部分をすべて省略し、最初の一払いだけを残したのが「ノ」です。',
    meaning: 'すなわち、の（助詞）、なんじ',
    dummyKanji: ['及', '力', '万']
  },
  {
    char: 'ハ',
    kanji: '八',
    part: '「八」の全体',
    originDetail: '「八（ハチ・ハ）」という漢字が、ほぼそのままカタカナの「ハ」になりました。ひらがなの「は」も同じく「八」の全体が崩れたものです。',
    strokeCount: 2,
    romaji: 'ha',
    type: 'full',
    typeName: '全体の変形',
    visualTips: '漢字の「八」そのものが、そのままカタカナの「ハ」として使われています。',
    meaning: 'やつ、八つ、ひろがる、わかれる',
    dummyKanji: ['人', '入', 'ハ']
  },
  {
    char: 'ヒ',
    kanji: '比',
    part: '「比」の左側の「匕」',
    originDetail: '「比（ヒ）」という漢字の左半分（「匕（さじ）」の部分）がそのまま取り出されて「ヒ」になりました。',
    strokeCount: 2,
    romaji: 'hi',
    type: 'part',
    typeName: '一部の省略',
    visualTips: '「比」は「匕」が二つ並んだ漢字です。その左側の「匕」を取り出して少し整えたのが「ヒ」です。',
    meaning: 'くらべる、ならぶ、等しい',
    dummyKanji: ['此', '皆', '批']
  },
  {
    char: 'フ',
    kanji: '不',
    part: '「不」の左上部分（最初の二画）',
    originDetail: '「不（フ）」という漢字の最初の一画（横棒）と二画（斜め左への払い）が取り出されて「フ」になりました。',
    strokeCount: 1,
    romaji: 'fu',
    type: 'part',
    typeName: '一部の省略',
    visualTips: '「不」の一番上の「フ」の部分だけを書き、下にある「縦棒」と「点」を省略したのが「フ」です。',
    meaning: '〜ず、打ち消し、よくない、〜でない',
    dummyKanji: ['下', '本', '歪']
  },
  {
    char: 'ヘ',
    kanji: '部',
    part: '「部」の旁（右側の「阝」の省略）',
    originDetail: '「部（ブ・ヘ）」という漢字の右側にある「おおざと（阝）」が草体となり、変形して「ヘ」になったとされています。※「平」の草書体からという説もあります。',
    strokeCount: 1,
    romaji: 'he',
    type: 'tsukuri',
    typeName: '旁（つくり・みぎ）',
    visualTips: '「部」の右側「阝」を流れるように書いた時の曲線が、シンプルな一山（へ）に変化しました。',
    meaning: 'わける、区分、グループ、へや',
    dummyKanji: ['都', '郭', '陪']
  },
  {
    char: 'ホ',
    kanji: '保',
    part: '「保」の右下部分（「木」の省略）',
    originDetail: '「保（ホ）」という漢字の右下部分（「木」に似た部分、または「口」の下の部分）が変形して「ホ」になりました。',
    strokeCount: 4,
    romaji: 'ho',
    type: 'part',
    typeName: '一部の省略',
    visualTips: '「保」の「にんべん（亻）」と「只」を取り去り、一番下の「ホ（木に似た四画）」だけをきれいに残したのが「ホ」です。',
    meaning: 'たモつ、まもる、やすらか',
    dummyKanji: ['休', '体', '佐']
  },
  {
    char: 'マ',
    kanji: '末',
    part: '「末」の上部、または「万」の草書体',
    originDetail: '「末（マツ・マ）」の上部の横棒二本と斜めの線、あるいは「万（マン・マ）」を草書体（くずし字）で書いた形から「マ」になりました。',
    strokeCount: 2,
    romaji: 'ma',
    type: 'part',
    typeName: '一部の省略 / 草書変形',
    visualTips: '「末」の上部二本の横棒を繋げて書き、そのまま左下に払うと「マ」の形になります。',
    meaning: 'すえ、はし、終わり、細かい',
    dummyKanji: ['万', '方', '未']
  },
  {
    char: 'ミ',
    kanji: '三',
    part: '「三」の全体（斜めの三本線）',
    originDetail: '「三（サン・ミ）」という漢字が、素早く書く流れの中で右斜め下にスッと払う三本の線になり、「ミ」になりました。',
    strokeCount: 3,
    romaji: 'mi',
    type: 'full',
    typeName: '全体の変形',
    visualTips: '「三」の横にまっすぐな三本の棒を、右上から左下へ向けて並べて書いたものが「ミ」です。',
    meaning: 'み、みっつ、三番目',
    dummyKanji: ['二', '川', '王']
  },
  {
    char: 'ム',
    kanji: '牟',
    part: '「牟」の上部（「厶」に似た部分）',
    originDetail: '「牟（ボウ・ム）」という漢字の上部にある「厶（む・ござの）」の部分が、そのまま「ム」になりました。※「無」の草書体からという説もあります。',
    strokeCount: 2,
    romaji: 'mu',
    type: 'part',
    typeName: '一部の省略',
    visualTips: '「牟」の下の「牛」の部分を取り除き、上の「ム（厶）」だけを残したのがカタカナの「ム」です。',
    meaning: '牛の鳴き声、むさぼる、大きい、奪う',
    dummyKanji: ['牛', '弁', '卑']
  },
  {
    char: 'メ',
    kanji: '女',
    part: '「女」の右下部分（交差する二画）',
    originDetail: '「女（ジョ・め）」という漢字の右下にある、斜めの線が交差する二画が抜き出されて「メ」になりました。',
    strokeCount: 2,
    romaji: 'me',
    type: 'part',
    typeName: '一部の省略',
    visualTips: '「女」の最初の一画（くの字）を省略し、残りの交差する二画だけをシンプルに書いたのが「メ」です。',
    meaning: 'おんな、め、めす',
    dummyKanji: ['如', '好', '妄']
  },
  {
    char: 'モ',
    kanji: '毛',
    part: '「毛」の全体（若干の変形）',
    originDetail: '「毛（モウ・け）」という漢字全体の形が、少し角が落とされて簡略化され、カタカナの「モ」になりました。',
    strokeCount: 3,
    romaji: 'mo',
    type: 'full',
    typeName: '全体の変形',
    visualTips: '「毛」の最後、右下へ大きく跳ねる部分をまっすぐな横引きに簡略化したのが「モ」です。ひらがなの「も」も同じく「毛」が由来です。',
    meaning: 'け、はね、おもう、わずかな量',
    dummyKanji: ['手', '尾', '筆']
  },
  {
    char: 'ヤ',
    kanji: '也',
    part: '「也」の全体（崩し・変形）',
    originDetail: '「也（ヤ）」という漢字の草書体（くずし字）が、書きやすく角張った形に整理されて「ヤ」になりました。',
    strokeCount: 2,
    romaji: 'ya',
    type: 'full',
    typeName: '全体の変形',
    visualTips: '「也」の一画目を少し斜め上に引き、二画目を省略して、三画目の縦から右に払う部分を組み合わせたのが「ヤ」です。ひらがなの「や」も同じく「也」が由来です。',
    meaning: 'なり（〜である）、また、なり（語尾の助詞）',
    dummyKanji: ['地', '池', '他']
  },
  {
    char: 'ユ',
    kanji: '由',
    part: '「由」の上部、または草書体の省略',
    originDetail: '「由（ユウ・ユ）」という漢字の草書体（くずし字）において、上部の「コ」の字に似た囲み部分が強調され「ユ」になりました。※「弓」の変形という説もあります。',
    strokeCount: 2,
    romaji: 'yu',
    type: 'part',
    typeName: '一部の省略 / 草書変形',
    visualTips: '「由」の下部をすっきりと略し、上部の「ユ」に似た形を強調して書いたものです。ひらがなの「ゆ」も「由」の全体が草書化したものです。',
    meaning: 'よし、わけ、もとづく、通る',
    dummyKanji: ['油', '笛', '宙']
  },
  {
    char: 'ヨ',
    kanji: '与',
    part: '「与」の全体（簡略化された全体の形）',
    originDetail: '「與」の略字である「与（ヨ）」という漢字全体の形が、そのままカタカナの「ヨ」になりました。',
    strokeCount: 3,
    romaji: 'yo',
    type: 'full',
    typeName: '全体の変形',
    visualTips: '「与」の一画目の横棒、二画目のカギ、三画目の横棒のバランスを整え、Eを反転させたような「ヨ」の形になりました。ひらがなの「よ」も同じく「与」が由来です。',
    meaning: 'あたえる、くみする、ともに、〜と（助詞）',
    dummyKanji: ['写', '汚', '互']
  },
  {
    char: 'ラ',
    kanji: '良',
    part: '「良」の右上部分（最初の二画）',
    originDetail: '「良（リョウ・ら）」という漢字の最上部にある、点と横棒（「ラ」に似た部分）が取り出されて「ラ」になりました。',
    strokeCount: 2,
    romaji: 'la',
    type: 'part',
    typeName: '一部の省略',
    visualTips: '「良」の上の点と横棒の二画をそのまま「ラ」として使い、下部の複雑な「いい」の部分をすべて省略しました。',
    meaning: 'よい、すぐれる、まこと',
    dummyKanji: ['食', '娘', '恨']
  },
  {
    char: 'リ',
    kanji: '利',
    part: '「利」の旁（右側の「刂」）',
    originDetail: '「利（リ）」という漢字の右側（旁＝つくり）にある「りっとう（刂）」が、そのままカタカナの「リ」になりました。',
    strokeCount: 2,
    romaji: 'ri',
    type: 'tsukuri',
    typeName: '旁（つくり・みぎ）',
    visualTips: '「利」の左側の「のぎへん（禾）」を取り除き、右側の「りっとう（刂）」だけを残したのが「リ」です。ひらがなの「り」も同じく「利」全体が崩れたものです。',
    meaning: 'きく、するどい、もうけ、つごうがよい',
    dummyKanji: ['和', '私', '秋']
  },
  {
    char: 'ル',
    kanji: '流',
    part: '「流」の右下部分（最後の二画）',
    originDetail: '「流（リュウ・ル）」という漢字の右下にある、最後を飾る二つの払い（「ル」に似た部分）が取り出されて「ル」になりました。',
    strokeCount: 2,
    romaji: 'ru',
    type: 'part',
    typeName: '一部の省略',
    visualTips: '「流」の「さんずい（氵）」や上の「充」に似た部分を取り除き、一番下の「ル（川の下部）」だけを残したのが「ル」です。',
    meaning: 'ながれる、ながす、ただよう、系統',
    dummyKanji: ['硫', '充', '梳']
  },
  {
    char: 'レ',
    kanji: '礼',
    part: '「礼（禮）」の旁（右側の「乚」）',
    originDetail: '「礼（レイ・レ）」という漢字の右側にある「乚（おつ・まがる）」の部分が、そのまま「レ」になりました。',
    strokeCount: 1,
    romaji: 're',
    type: 'tsukuri',
    typeName: '旁（つくり・みぎ）',
    visualTips: '「しめすへん（礻・ネ）」を取り去り、右側の「乚（レに似た一画）」だけを残したのが「レ」です。',
    meaning: 'れい、おじぎ、うやまう、のり、社会の秩序',
    dummyKanji: ['札', '乱', '孔']
  },
  {
    char: 'ロ',
    kanji: '呂',
    part: '「呂」の上半分（上の「口」）',
    originDetail: '「呂（ロ）」という漢字は「口（くち）」が縦に二つ並んでいますが、その上の「口」の部分がそのまま「ロ」になりました。',
    strokeCount: 3,
    romaji: 'ro',
    type: 'part',
    typeName: '一部の省略',
    visualTips: '「呂」の二つの口のうち、上の一つの「口」を取り出して少し整えたのが「ロ」です。日本語の「くち（口）」と同じ形です。',
    meaning: 'せぼね、音律、呂律（ろれつ）',
    dummyKanji: ['宮', '品', '岩']
  },
  {
    char: 'ワ',
    kanji: '和',
    part: '「和」の右上部分（最初の二画の崩し）',
    originDetail: '「和（ワ）」という漢字の右上、または草書体の一部の崩しから「ワ」になりました。※「輪」の草書体からという説もあります。',
    strokeCount: 2,
    romaji: 'wa',
    type: 'part',
    typeName: '一部の省略 / 草書変形',
    visualTips: '「和」の左の「禾」と右の「口」が繋がるように書かれた草書の形から、上の冠の部分が「ワ」の形として独立しました。ひらがなの「わ」も「和」の全体が草書化したものです。',
    meaning: 'なごむ、おだやか、あわせる、日本のこと',
    dummyKanji: ['積', '種', '程']
  },
  {
    char: 'ヲ',
    kanji: '乎',
    part: '「乎」の全体（または上部）の草書体',
    originDetail: '「乎（コ・ヲ）」という漢字の草書体（くずし字）が、角張ったカタカナの「ヲ」に変化しました。',
    strokeCount: 3,
    romaji: 'wo',
    type: 'full',
    typeName: '全体の変形',
    visualTips: '「乎」を草書で素早く書くと、上の横棒と真ん中の結び、左右の払いが繋がり、それが楷書風に整理されて「ヲ」になりました。ひらがなの「を」も同じく「乎」が由来です。',
    meaning: '〜か、〜や（疑問や感嘆を表す助詞・助字）',
    dummyKanji: ['呼', '平', '半']
  },
  {
    char: 'ン',
    kanji: '无',
    part: '「无」の草書体',
    originDetail: '「无（ブ・む・なし）」という漢字の草書体（くずし字）が、さらに省略されて現在のカタカナの「ン」になりました。※「二」や「三」の草体からという説もあります。',
    strokeCount: 2,
    romaji: 'n',
    type: 'full',
    typeName: '全体の変形',
    visualTips: '「无」を素早く草書で崩して書くときの筆の払いと点の動きが、最終的に点と右上がりの一払い（ン）に整理されました。',
    meaning: '〜がない、なし、存在しない（「無」の古字）',
    dummyKanji: ['無', '天', '元']
  }
];

export const getKatakanaByChar = (char: string): KatakanaData | undefined => {
  return katakanaList.find(item => item.char === char);
};

export const getKatakanaByKanji = (kanji: string): KatakanaData | undefined => {
  return katakanaList.find(item => item.kanji === kanji);
};
